version: '3'
services:
  mailer:
    restart: on-failure
    build:
      context: ./
      dockerfile: urlpdfmailer.dockerfile
    volumes:
      - urlpdfmailer_log:/usr/src/urlpdfmailer/log
  logserver:
    restart: on-failure
    build:
      context: ./
      dockerfile: httptextfileserver.dockerfile

    volumes:
      - urlpdfmailer_log:/usr/src/log
    ports:
     - 1234:1234
volumes:
  urlpdfmailer_log:
